stages:
  prepare:
    cmd: python3 src/prepare.py
    deps:
      - src/prepare.py
    params:
      - prepare.split_ratio
      - prepare.random_state
    outs:
      - data/prepared

  train:
    cmd: python3 src/train.py
    deps:
      - src/train.py
      - data/prepared/train.csv
    params:
      - train.n_estimators
      - train.max_depth
      - train.random_state
    outs:
      - models/model.pkl
      - models/model_columns.pkl

  evaluate:
    cmd: python3 src/evaluate.py
    deps:
      - src/evaluate.py
      - data/prepared/test.csv
      - models/model.pkl
      - models/model_columns.pkl
    metrics:
      - metrics.json:
          cache: false